# Generated by Django 3.1.1 on 2020-09-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('sender', 'send'), ('accepted', 'accepted')], max_length=8),
        ),
    ]
